services:

  app:
    build: .
    restart: on-failure

  caddy:
    image: caddy
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
