sender_email: "your_email@example.com"
sender_login: "your_login@example.com"
sender_password: "your_password"
smtp_server: "smtp.example.com"
smtp_port: 587
turnstile_secret: "your_secret"
submission_points:
  - submission_url: "/abc"
    success_url: "http://example.com/success"
    error_url: "http://example.com/error"
    subject: "Form Submission"
    to_email: "recipient@example.com"
